### ISSUE TITLE
chore: add caching to all static assets 

### ISSUE THREAD

**Issue by umutuzgur** [checkly/checklyhq.com#140]
We are currently not caching anything on the marketing website and therefore, the images are flickering when a page is loaded the second time or simply when you navigate through the webpage.

Caching is pretty simple on vercel. We simply need to put the json below to the `headers` array in the `vercel.json` file
```json
{
      "source": "/static/(.*)",
      "headers": { "key": "cache-control", "value": "max-age=315360000, s-maxage=315360000" }
}
```

The problem is that we are not serving the static assets from a `/static` prefix. An example would be this url `https://www.checklyhq.com/landing/case-studies@2x.7772d82a.webp`. This makes the `source` regex difficult and we shouldn't try to address this. We need to serve all the things under the `static` folder in the repo also from the path of `https://www.checklyhq.com/static/*` and then add the cache header in the `vercel.json`

- [ ] Serve all static files from `https://www.checklyhq.com/static/*` or `https://www.checklyhq.com/public/static/*`
- [ ] Add the cache header object to the vercel.json file

**Comment by RistoBIn** [comment]
I update all assets url with the prefix "/images".
So, all assets serve from https://www.checklyhq.com/images/*.
In this case, do we have to update vercel.json too?
