### ISSUE TITLE
bug: top menubar padding is off

### ISSUE THREAD

**Issue by orcunilbeyli** [checkly/checklyhq.com#153]
On tablet and mobile, there is no left and right padding. It should follow the design.

Live:
![image](https://user-images.githubusercontent.com/1042651/129898547-5dafbc6f-6e78-4d05-829c-d7454ffce138.png)

Design:
![image](https://user-images.githubusercontent.com/1042651/129898594-e9bd4fd3-4416-4904-b3aa-0c5d82b545d2.png)

**Comment by RistoBIn** [comment]
Resolved PR #171
