### ISSUE TITLE
change: product navigation menu

### ISSUE THREAD

**Issue by orcunilbeyli** [checkly/checklyhq.com#184]
Please update the product navigation with the following design.

![image](https://user-images.githubusercontent.com/1042651/132715012-45eb4dcd-992d-441b-a0d8-3cb30f2d4ddf.png)

https://www.figma.com/file/et2KLDMVOPb0xeAmXFJXok/checklyhq.com?node-id=2199%3A11010

`product-dropdown-updated`

**Comment by RistoBIn** [comment]
Updated in the PR #185
