### ISSUE TITLE
[Auth/Invite Bug] Reinvited account cannot log in successfully

### ISSUE THREAD

**Issue by janos1uphealth** [checkly/checklyhq.com#281]
The scenario is the following:

1. Invite an email address to your Team through the Team page 
 - goto https://app.checklyhq.com/settings/account/team
 - hit the 'Invite users' button
 - grant permissions
2. User receives the email
3. User joins the Org
- hits 'Login or Sign up to join Org'
- uses google auth or creates a password
4. User signs in
5. Remove that user's access through the Team page
- remove user by hitting the Trash icon: Revoke access for this user
7. Invite an email address again to your Team through the Team page
8. User clears browser cache and cookies
9. User joins the org again and authenticates itself
- either through google or the previously existed password
- Note: no password reset prompt shows up
10. User signs in

**Result**: An endless auth loop
- The 'code' in the URL keeps changing, user gets redirected to the URL with a newly generated code and the process never resolves
- Example url: https://app.checklyhq.com/?code=eWfkIJHp2pfaVWoo&state=akxxMnpDRkEwN0IzXy5NVjVTaTlQZ0pWNkl4cjVnQnA0cUktRGVGZUsxQw%3D%3D

**Comment by tnolet** [comment]
@janos1uphealth yes, this is a known bug. It's happening due to some legacy login code that we are tackling at the moment. I will actually keep this ticket open so we can also publicly track it here.

**Comment by tnolet** [comment]
@janos1uphealth Ah, sorry! I saw this issue was on our main website repo. I will close it here. 
For those reading along or finding this issue 5 years from now: we are chatting to Janos through our support channel and will fix this.
