### ISSUE TITLE
[feature request] add dark mode to follow prefers-color-scheme

### ISSUE THREAD

**Issue by foss-** [checkly/checklyhq.com#291]
https://caniuse.com/prefers-color-scheme is at 93% global. Would be nice to have a dark css theme checking this preference and following it.

Thanks for considering.

**Comment by ianaya89** [comment]
Hi @foss-, we already have an [open issue](https://github.com/checkly/public-roadmap/issues/124) in our Public Roadmap.
You can follow up on the status of this feature request there.
Feel free to add any feedback or comments you consider relevant.

Thank you!
