### ISSUE TITLE
Pricing page update

### ISSUE THREAD

**Issue by Haubersch** [checkly/checklyhq.com#41]
@RistoBIn we need to do some updates on the pricing page https://www.checklyhq.com/pricing. Ideally we can do it before the weekend. See below:

1. SAML/SSO is now available for all paid plans. Not only Enterprise. Can you replace "SAML/SSO" under Enterprise section with "SLA".
![Pricing-Site-Update](https://user-images.githubusercontent.com/7566904/116522146-21975b80-a8d5-11eb-82c5-369815ba7566.png)
and also change it in the table:
![Bildschirmfoto 2021-04-29 um 10 17 46](https://user-images.githubusercontent.com/7566904/116522509-9074b480-a8d5-11eb-87a8-c32c5c327ee8.png)

2. We have new check intervals. API checks are now very 10 seconds and browser checks every 60 seconds. Please change for all plans. You also have to change it for the pop-up when you hover over the link.
![Pricing-Update-2](https://user-images.githubusercontent.com/7566904/116522279-4f7ca000-a8d5-11eb-9fd8-9ae0943cfffe.png)

3. Lastly we want to update the Q&A section. Can you please just delete the marked questions
![Bildschirmfoto 2021-04-29 um 10 11 41](https://user-images.githubusercontent.com/7566904/116522680-c154e980-a8d5-11eb-948e-7d82b8146ec7.png)
Also, we have a mistake in one of the answers. Free trials include 50,000/5,000 and 100,000/10,000
![Bildschirmfoto 2021-04-29 um 10 15 14](https://user-images.githubusercontent.com/7566904/116522771-d92c6d80-a8d5-11eb-8dbb-8a238bf9a6e2.png)

**Comment by hlenke** [comment]
solved. hence closing.
