### ISSUE TITLE
docs: 

### ISSUE THREAD

**Issue by fabiandevia** [checkly/checklyhq.com#533]
### What is the improvement or update you wish to see?

Google chat alerts API endpoint

### Is there any context that might help us understand?

https://chat.googleapis.com/v1/spaces/{{GOOGLE_SPACE_ID}}/messages?key={{GOOGLE_KEY}}&token={{GOOGLE_TOKEN}}

This is an example of a full alert body:
{"text": "{{ALERT_TITLE}} {{ALERT_TYPE}} {{STARTED_AT}} ({{RESPONSE_TIME}}ms) {{RESULT_LINK}}"}

**Comment by ianaya89** [comment]
Hi @fabiandevia, can you add more context to this issue? Thanks!

**Comment by fabiandevia** [comment]
@ianaya89 My contribution is the integration of the webhook for google chat.
