### ISSUE TITLE
docs: Headless Automation Guides / Basics performance - Details about Chromium specific stuff?

### ISSUE THREAD

**Issue by airbr** [checkly/checklyhq.com#638]
### What is the improvement or update you wish to see?

https://www.checklyhq.com/learn/headless/basics-performance/ Is a great resource on the exact topic I was researching today, which was how to use Playwright with libraries to gather information about web vitals.

However, it did not seem super clear that the example code for many of the examples really is chromium specific? It is common to run multiple browsers in Playwright tests and it took me a while to realize the code appears to have some kind of chrome specific nature, for example the code to determine the LCP timing.

I am unsure myself what the cause of the difference is, but any help would do, and mainly I make this issue just to say thanks for covering this topic at all it is one of the few resources I found on an initial look today. 

### Is there any context that might help us understand?

This code appears to fail in webkit and safari for me, and its not clear why. 

```
const largestContentfulPaint = await page.evaluate(() => {
    return new Promise((resolve) => {
      new PerformanceObserver((l) => {
        const entries = l.getEntries();
        // the last entry is the largest contentful paint
        const largestPaintEntry = entries.at(-1);
        resolve(largestPaintEntry.startTime);
      }).observe({
        type: 'largest-contentful-paint',
        buffered: true
      })
    })
  })

  console.log(parseFloat(largestContentfulPaint)) // 1139.39
  ```

### Does the docs page already exist? Please link to it.

https://www.checklyhq.com/learn/headless/basics-performance/

**Comment by stefanjudis** [comment]
Hello Morgan, thanks for reporting this issue. 

> However, it did not seem super clear that the example code for many of the examples really is chromium specific?

This is very valuable feedback and we'll be redoing the entire section in a month or two. I'll try to keep it in mind to call out that the snippets are tested only in Chromium (or add notes about support).

> I am unsure myself what the cause of the difference is

In this particular case, [it looks like webkit isn't supporting the `largest-contentful-paint` metric]() so the promise never resolves. [I also checked google's `web-vitals` lib and it looks like there's no reliable way to determine LCP in webkit](https://github.com/GoogleChrome/web-vitals#browser-support).

I'll be close this issue, but let me know if I can help further. :)
